trigger:
- master
pool:
  name: Default

variables:
  AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL: true

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo "Cleanup Modules Variable: $env:AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL"
    $PSVersionTable
    pwsh -Command '$PSVersionTable'
  displayName: 'Verify PowerShell Core'

- script: |
    Remove-Item -Path "$env:LOCALAPPDATA\Microsoft\Windows\PowerShell\Modules\*" -Recurse -Force -ErrorAction SilentlyContinue
    Import-Module Microsoft.PowerShell.Security -Force
    node -v
    npm -v
    echo "Environment Info: $env:COMPUTERNAME"
  displayName: "Log Node.js Environment"

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

