trigger:
- master

pool:
  name: Default

variables:
  AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL: true

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    # Clear any old modules and ensure necessary modules are imported
    Remove-Item -Path "$env:LOCALAPPDATA\Microsoft\Windows\PowerShell\Modules\*" -Recurse -Force -ErrorAction SilentlyContinue
    try {
      # Explicitly load the PowerShell Security module
      Import-Module Microsoft.PowerShell.Security -Force -ErrorAction Stop
    } catch {
      Write-Host "Error importing PowerShell.Security module: $_"
    }
    
    # Log Node.js and npm versions
    node -v
    npm -v
    
    # Log Environment Info
    echo "Environment Info: $env:COMPUTERNAME"
  displayName: "Log Node.js Environment"

- script: |
    # Run npm install and build
    npm install
    npm run build
  displayName: 'npm install and build'
